/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demo_FenShim */

#ifndef _Included_demo_FenShim
#define _Included_demo_FenShim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demo_FenShim
 * Method:    fenOpen
 * Signature: (IILjava/lang/String;Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_demo_FenShim_fenOpen
  (JNIEnv *, jclass, jint, jint, jstring, jobject);

/*
 * Class:     demo_FenShim
 * Method:    fenLoop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_demo_FenShim_fenLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     demo_FenShim
 * Method:    fenClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_demo_FenShim_fenClose
  (JNIEnv *, jclass, jlong);

/*
 * Class:     demo_FenShim
 * Method:    fenKey
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_demo_FenShim_fenKey
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     demo_FenShim
 * Method:    fenSleep
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_demo_FenShim_fenSleep
  (JNIEnv *, jclass, jint);

/*
 * Class:     demo_FenShim
 * Method:    fenTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_demo_FenShim_fenTime
  (JNIEnv *, jclass);

/*
 * Class:     demo_FenShim
 * Method:    fenAudioOpen
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_demo_FenShim_fenAudioOpen
  (JNIEnv *, jclass);

/*
 * Class:     demo_FenShim
 * Method:    fenAudioAvail
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_demo_FenShim_fenAudioAvail
  (JNIEnv *, jclass, jlong);

/*
 * Class:     demo_FenShim
 * Method:    fenAudioWrite
 * Signature: (JLjava/nio/FloatBuffer;I)V
 */
JNIEXPORT void JNICALL Java_demo_FenShim_fenAudioWrite
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     demo_FenShim
 * Method:    fenAudioClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_demo_FenShim_fenAudioClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
